#!/bin/sh
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

function red {
    printf "${RED}$@${NC}\n"
}

function green {
    printf "${GREEN}$@${NC}\n"
}

function yellow {
    printf "${YELLOW}$@${NC}\n"
}

while getopts u:p:h:k: flag
do
    case "${flag}" in
        u) user=${OPTARG};;
        p) port=${OPTARG};;
        h) host=${OPTARG};;
        k) key=${OPTARG};;
    esac
done

if [ -z "$user" ] 
then 
    user="root"; 
fi

if [ -z "$port" ] 
then 
    port="22"; 
fi

if [ -z "$host" ] 
then 
    red "⚠ Parameter 'host' is not defined. Use flag -h"
    exit 1 
fi

if [ -z "$key" ] 
then 
    if [ -z "$SSH_RUN_PRIVATE_KEY"]
    then
        red "⚠ Path to private key is not defined"
        red "Use flag -k or global variable \$SSH_RUN_PRIVATE_KEY as default" 
        exit 1
    fi
    key="$SSH_RUN_PRIVATE_KEY"
    
fi

if [ ! -f "$key" ]; then
    red "Private key file does not exist"
    red "Path: $key"
    exit 1
fi

chmod 600 $key

cat <<EOF > ~/.ssh/config
Host $host
 StrictHostKeyChecking no
 User $user
 Port $port
 IdentityFile $key
EOF

cat <<EOF > ~/ssh_run.variables
export SSH_RUN_USERNAME_service_variable=$user
export SSH_RUN_HOSTNAME_service_variable=$host
export SSH_RUN_PORT_service_variable=$port
export SSH_RUN_KEY_service_variable=$key
EOF

green "The settings were successfully set"      
yellow "Username: $user";
yellow "Host: $host";
yellow "Port: $port";
yellow "Key: $key";




















# cat <<EOF > /ssh_run_variables
# export SSH_RUN_USERNAME=$1
# export SSH_RUN_HOSTNAME=$2
# export SSH_RUN_PRIVATE_KEY=$3
# export SSH_RUN_USERNAME=$4
# EOF


# while getopts "u:h:p:k" opt
# do
#    case "$opt" in
#       a ) user="$OPTARG" ;;
#       b ) host="$OPTARG" ;;
#       c ) port="$OPTARG" ;;
#       ? ) key ;; # Print helpFunction in case parameter is non-existent
#    esac
# done

# cat <<EOF ~/.ssh/config
# Host $2
#  StrictHostKeyChecking no
#  User $1
#  Port $4
 

# export SSH_RUN_HOSTNAME=$1
# export SSH_RUN_PRIVATE_KEY=$1
# EOF


# exit 0

# # #!/bin/bash
# # function ssh_init() {
# #     SSH_PRIVATE_KEY="$1"
# #     SSH_KNOWN_HOSTS="$2"
# #     test -n "$SSH_PRIVATE_KEY" || ( echo "missing variable SSH_PRIVATE_KEY" && exit 1)
# #     test -n "$SSH_KNOWN_HOSTS" || ( echo "missing variable SSH_KNOWN_HOSTS" && exit 1)
# #     which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
# #     eval $(ssh-agent -s)
# #     echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
# #     mkdir -p ~/.ssh
# #     chmod 700 ~/.ssh
# #     ssh-keyscan -H "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
# #     chmod 644 ~/.ssh/known_hosts
# # }
# # function ssh_run() {
# #     USER=$1
# #     HOST=$2
# #     PKEY=$3
# #     COMMAND=$4
# #     ssh_init "$PKEY" $HOST
# #     ssh $USER@$HOST $COMMAND
# # }